### ISSUE TITLE
How do you use this? Which files do what and how do I even begin?

### ISSUE THREAD

**Issue by cadennabors** [Martyn0324/Hakisa#4]

**Comment by Martyn0324** [comment]
Take a look at the Successful Prototype in the Tests branch. The modules you'll need are the ones that are imported there.

If you want to use the Study mode, you'll need a dataset with images of your game and their respective labels.

The code in the jupyter notebook provide examples on how you can run the code for the games [Jigoku Kisetsukan: Sense of the Seasons](https://store.steampowered.com/app/368950/Jigoku_Kisetsukan_Sense_of_the_Seasons/) and [Bullet Heaven 2](https://store.steampowered.com/app/412670/Bullet_Heaven_2/)

If you want to run Hakisa in a different game, you'll have to adapt the code in order to do so.

**Comment by KlausikPL** [comment]
"If you want to run Hakisa in a different game, you'll have to adapt the code in order to do so." can you give quick tutorial what change in the code to adapt to game like "Forza Horizon 5" or "Fallout 76"?

**Comment by Martyn0324** [comment]
> "If you want to run Hakisa in a different game, you'll have to adapt the code in order to do so." can you give quick tutorial what change in the code to adapt to game like "Forza Horizon 5" or "Fallout 76"?

No, sorry, I really don't have time for meaningful projects right now.

But the modifications aren't that many. Forza Horizon probably uses the keyboard for commands, so you can get some ideas from Jigoku Kisetsukan code. Getting the reward in this case would be a bit tricky, as you would probably need to get your race position and the race map to provide a reward for Hakisa. You could use a Reward Model an capture screen regions for this. I think there's also some code in this repository providing some ideas.

For Fallout 76, as well as for sandbox games in general, I don't know how one could implement Reinforcement Learning, as these games don't have a clear objective for a reward function and they're basically a world where the player makes their game. So, an AI to play this kind of game would have to be able to plan what it's going to do, plan how to do it and execute it step by step.

**Comment by KlausikPL** [comment]
okay thanks for help
